# .pre-commit-config.yaml
repos:
-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: python -m pytest
        language: system
        pass_filenames: false
        always_run: true
        
    -   id: pytest-validation
        name: pytest-validation
        entry: python -m pytest tests/unit/test_validation_module.py tests/unit/test_metrics.py -v
        language: system
        files: ^(backtester/validation/|tests/unit/test_validation_module.py|tests/unit/test_metrics.py)
        pass_filenames: false
        
    -   id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        exclude: ^(venv/|\.venv/|\.git/)
