"""
Constants used throughout the backtesting system.
"""

from enum import Enum, auto


class SignalType(Enum):
    """Types of trading signals that can be generated by strategies."""
    BUY = auto()
    SELL = auto()
    HOLD = auto()


class TimeFrame(Enum):
    """Supported timeframes for market data."""
    MINUTE_1 = "1m"
    MINUTE_5 = "5m"
    MINUTE_15 = "15m"
    HOUR_1 = "1h"
    HOUR_4 = "4h"
    DAY_1 = "1d"
    WEEK_1 = "1w" 